### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by jedugsem** [arch-beryllium/build#1]
not working says :
```log
+ chmod +x /tmp/tmp.RYVT5RvZu3/install
+ do_chroot /install
+ cmd=/install
+ mount -o bind /dev /tmp/tmp.RYVT5RvZu3/dev
+ chroot /tmp/tmp.RYVT5RvZu3 mount -t proc proc /proc
chroot: der Befehl „mount“ konnte nicht ausgeführt werden: Datei oder Verzeichnis nicht gefunden
+ true
+ chroot /tmp/tmp.RYVT5RvZu3 mount -t sysfs sys /sys
chroot: der Befehl „mount“ konnte nicht ausgeführt werden: Datei oder Verzeichnis nicht gefunden
+ true
+ chroot /tmp/tmp.RYVT5RvZu3 mount -t tmpfs none /tmp
chroot: der Befehl „mount“ konnte nicht ausgeführt werden: Datei oder Verzeichnis nicht gefunden
+ true
+ chroot /tmp/tmp.RYVT5RvZu3 /install
chroot: der Befehl „/install“ konnte nicht ausgeführt werden: Datei oder Verzeichnis nicht gefunden
+ cleanup
+ '[' -e /tmp/tmp.RYVT5RvZu3/proc ']'
```

**Comment by provokateurin** [comment]
Can you please send the full log? I suspect the rootfs wasn't unpacked properly or something like that, but I can only confirm that if I see the full log.
(Side question: How did you find out about this project?)

**Comment by jedugsem** [comment]
I solved it dont know how to make a merge request here, i had to put cp /usr/bin/qemu-aarch64-static "$DEST"/usr/bin at the start of the do_chroot function. I found out about this because i tryed postmarketos and played a little bit with it but i used manjaro / arch on my laptop and know ABS better than teir package format. In some chat Venji10  said that someone also works on arch for this phone so i googled. btw i'm also German but i think here english is better

**Comment by jedugsem** [comment]
next error which  i dont understand : 
xxhash-0.8.0-1-a...    69.6 KiB   195 KiB/s 00:00 [############] 100%
telegram-desktop...    21.4 MiB   898 KiB/s 00:24 [############] 100%
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
+ cleanup

soon i'll have the arch repo cloned takes so much time

**Comment by provokateurin** [comment]
Hm I saw some people doing that, but it was never necessary for my setup. In which line did you insert the copy?

**Comment by provokateurin** [comment]
> next error which i dont understand :
> xxhash-0.8.0-1-a... 69.6 KiB 195 KiB/s 00:00 [############] 100%
> telegram-desktop... 21.4 MiB 898 KiB/s 00:24 [############] 100%
> error: failed to commit transaction (unexpected error)
> Errors occurred, no packages were upgraded.
> 
> * cleanup
> 
> soon i'll have the arch repo cloned takes so much time

I think the download failed. Did you mirror the repos with my tool? Otherwise working with the script takes ages

**Comment by jedugsem** [comment]
I'm at community openssh so it will not take long anymore. Inserted it in between 15 and 16 in build.sh

**Comment by provokateurin** [comment]
15 and 16? That doesn't make sense

**Comment by jedugsem** [comment]
sry between 97 and 98 i have relative numbers in my vim. I know it's maybe not he best place because maybe i copies it twice or more but it is the simplest.
Mfg

**Comment by provokateurin** [comment]
Fixed in https://github.com/arch-beryllium/build/commit/8bfa90c0320c953e256a46af6ea650c944a1935a
