### ISSUE TITLE
Which hardware components work?

### ISSUE THREAD

**Issue by svenha** [arch-beryllium/build#3]
Is there any document that shows which hardware components work under Arch Linux? At the moment, I need only working speakers, microphone, battery charging and Wifi.

**Comment by provokateurin** [comment]
I initially wanted to say 'take a look at https://wiki.postmarketos.org/wiki/Xiaomi_Poco_F1_(xiaomi-beryllium)', but I see it's not completely up to date. The things you need should all work, although I personally never tested the microphone. Please check which display panel you have, as tianma is working with the kernel, but ebbg is currently out-of-tree/beeing worked on.

**Comment by provokateurin** [comment]
I'll probably add a table to the readme for this.

**Comment by provokateurin** [comment]
Wifi is currently behaving weird, especially because of some firmware issues.

**Comment by provokateurin** [comment]
Also 5GHz sometimes works and sometimes not...
