### ISSUE TITLE
Looking for linear set of instructions.

### ISSUE THREAD

**Issue by jordan89m** [arch-beryllium/build#4]
Firstly this is not so much an issue as it is a question. Though i suppose its an issue since i have to ask... Haha

Recently added Arch to my list of core daily distros. (Bringing my list to Void and Arch). And I quite enjoy it, but as for this project, im not seeing a core PKGBUILD to handle the entire process (the one in the meta repo complains of package requirements, which i assume comes from the mirror repo.)

Is there a main PKGBUILD repo I should be cloning over all others? And if not, how exactly does one get the serve.sh side of the mirror repo working correctly. That whole process is different than what im familiar with.

And if both of those are not the first step, then where the heck am i going wrong?! Hahahah

Kudos on at least putting something like this together. Id love to give my spare phone a new purpose.

**Comment by provokateurin** [comment]
Issues should be in this repo.

**Comment by provokateurin** [comment]
Hi, I guess the instructions could be a bit better.
There is no such main PKGBUILD in this project. This repo is the main repo.

Firstly you need to clone the mirror repo and create it with the update script in it (this will take a while as it's downloading around 24G of packages).
Then you clone this repo and while serving the mirror you build the rootfs for any flavour using the build script.
See the instructions in the readme.

If you get stuck just comment, I'll be happy to help you out!

**Comment by jordan89m** [comment]
Yeah my bad, had tabs open for a bunch of repos and didnt check first. 

Ive got all the packages downloaded. Cant quite wrap my head around the pacman conf stuff for serve.sh

**Comment by provokateurin** [comment]
What pacman conf stuff? The serve script just spins up a static webserver

**Comment by jordan89m** [comment]
Its probably the easiest of it all, but my recent adoption of Arch means it is the most foreign to me..

**Comment by jordan89m** [comment]
Well, after running serve.sh, if i run the build script, do i actually need to set up local mirror env variable? Also, serve.sh reads http://0.0.0.0:8080. Given im building on the same machine i could just connect to that no?

**Comment by provokateurin** [comment]
You don't have to configure anything for the mirror.
Just set `LOCAL_MIRROR=your.ip.address` (localhost also works for building but will disable upgrading on the device later).
Then run `sudo -E ./build.sh plasma-mobile` for example. The `-E` is needed to pass through the `LOCAL_MIRROR` env variable.

**Comment by provokateurin** [comment]
Yes, could also use http://0.0.0.0:8080

**Comment by jordan89m** [comment]
Build script is also throwing a an error during the chroot portion. Ill post it as soon as i can. At work right now.

**Comment by provokateurin** [comment]
Probably missing qemu user static aarch64? The instructions don't mention you need it. My bad

**Comment by jordan89m** [comment]
Nah ive got that already. And pigz which wasnt mentioned.

**Comment by provokateurin** [comment]
Ah yes that too. Maybe I should add checks for all dependencies

**Comment by jordan89m** [comment]
So for each mountpoint in the build_and_make_installer script, i get the error "chroot: failed to run command 'mount': Exec format error"

Running this straight from linux pc.

**Comment by jordan89m** [comment]
However PMOS worked fine, so I'm having a hard time believing its a chroot dependency of some sort... But at this point I cant even tell.

**Comment by jordan89m** [comment]
The good news is, the serve.sh works now as i can access the files from web browser on another device. 😃

**Comment by provokateurin** [comment]
That does sound like you have qemu not configured to emulate aarch64 binaries. pmOS does this manually, so you may have to lookup how it works for your distro.

**Comment by jordan89m** [comment]
I get the message on both arch and void. With either distros qemu static binaries or standalones from the web. Any leads on what to configure?

**Comment by jordan89m** [comment]
One thought im having is that it looks like the error is related to filesystem permissions on the $DEST folder created by mktemp -d. Are there any user account permissions that may need to be configured after a fresh install of arch?

**Comment by provokateurin** [comment]
Nope. You are on Arch on your host machine? For me to get it working I installed https://aur.archlinux.org/packages/qemu-user-static-bin

**Comment by provokateurin** [comment]
Mayve it already works then, but if not I'll see later when I'm at home what I have installed.

**Comment by jordan89m** [comment]
ill switch to that qemu bin and see how it goes. for now, here's the result of 'sudo -E ./build.sh plasma-mobile' prior to the cleanup steps (not really relevant...)

`+ ROOTFS=http://de4.mirror.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
++ basename http://de4.mirror.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
+ TARBALL=build/ArchLinuxARM-aarch64-latest.tar.gz
++ mktemp -d
+ DEST=/tmp/tmp.nFF2fXonbx
++ losetup -f
+ LOOP_DEVICE=/dev/loop0
+ ROOTFSIMG=build/plasma-mobile-rootfs.img
+ mkdir -p build
+ trap cleanup EXIT
+ set -ex
+ '[' -n '' ']'
+ download_sources
+ '[' '!' -f build/ArchLinuxARM-aarch64-latest.tar.gz ']'
+ wget http://de4.mirror.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz -O build/ArchLinuxARM-aarch64-latest.tar.gz
--2021-05-23 04:58:33--  http://de4.mirror.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
Resolving de4.mirror.archlinuxarm.org (de4.mirror.archlinuxarm.org)... 213.202.193.253
Connecting to de4.mirror.archlinuxarm.org (de4.mirror.archlinuxarm.org)|213.202.193.253|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 574731199 (548M) [application/octet-stream]
Saving to: ‘build/ArchLinuxARM-aarch64-latest.tar.gz’

build/ArchLinuxARM-aar 100%[=========================>] 548.11M  1.74MB/s    in 6m 10s  

2021-05-23 05:04:43 (1.48 MB/s) - ‘build/ArchLinuxARM-aarch64-latest.tar.gz’ saved [574731199/574731199]

+ setup_clean_rootfs
+ rm -f build/plasma-mobile-rootfs.img
+ fallocate -l 5120M build/plasma-mobile-rootfs.img
+ losetup -P /dev/loop0 build/plasma-mobile-rootfs.img
+ mkfs.ext4 -L ALARM /dev/loop0
mke2fs 1.46.2 (28-Feb-2021)
Discarding device blocks: done                            
Creating filesystem with 1310720 4k blocks and 327680 inodes
Filesystem UUID: d95f52b5-e73e-4b26-ba87-05d74e77540f
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

+ mount /dev/loop0 /tmp/tmp.nFF2fXonbx
+ build_rootfs
+ tar --use-compress-program=pigz --same-owner -xpf build/ArchLinuxARM-aarch64-latest.tar.gz -C /tmp/tmp.nFF2fXonbx
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
+ rm -rf /tmp/tmp.nFF2fXonbx/etc/resolv.conf
+ cp overlay/etc overlay/opt overlay/usr /tmp/tmp.nFF2fXonbx -r
+ '[' -n 'http://192.168.43.173:8080/$repo/$arch' ']'
+ cp /tmp/tmp.nFF2fXonbx/etc/pacman.conf /tmp/tmp.nFF2fXonbx/etc/pacman.conf.bak
+ cp /tmp/tmp.nFF2fXonbx/etc/pacman.d/mirrorlist /tmp/tmp.nFF2fXonbx/etc/pacman.d/mirrorlist.bak
+ sed -i 's/Server = .*/Include = \/etc\/pacman\.d\/mirrorlist/' /tmp/tmp.nFF2fXonbx/etc/pacman.conf
+ printf 'Server = %s' 'http://192.168.43.173:8080/$repo/$arch'
+ cat
++ printf ' %s' ui-plasma-mobile-meta tweaks-plasma-mobile tweaks-desktop-files bootsplash
++ printf ' %s'
+ chmod +x /tmp/tmp.nFF2fXonbx/install
+ do_chroot /install
+ cmd=/install
++ which qemu-aarch64-static
+ cp /usr/bin/qemu-aarch64-static /tmp/tmp.nFF2fXonbx/usr/bin
+ mount -o bind /dev /tmp/tmp.nFF2fXonbx/dev
+ chroot /tmp/tmp.nFF2fXonbx mount -t proc proc /proc
chroot: failed to run command ‘mount’: Exec format error
+ true
+ chroot /tmp/tmp.nFF2fXonbx mount -t sysfs sys /sys
chroot: failed to run command ‘mount’: Exec format error
+ true
+ chroot /tmp/tmp.nFF2fXonbx mount -t tmpfs none /tmp
chroot: failed to run command ‘mount’: Exec format error
+ true
+ chroot /tmp/tmp.nFF2fXonbx mount -t tmpfs none /var/cache/pacman/pkg
chroot: failed to run command ‘mount’: Exec format error
+ true
+ chroot /tmp/tmp.nFF2fXonbx /install
chroot: failed to run command ‘/install’: Exec format error
`

**Comment by jordan89m** [comment]
Ah ha! Disregard, it was the binfmt-qemu requirement of the static binary you linked. All is working now. I'll report back once the flash goes well. I also have some stuff to contribute, though it likely needs a little work first. I'd rather it went to an Arch-based project than PMOS any day, so this is good news!

**Comment by provokateurin** [comment]
Nice! I'm always open for any stuff, this is/was also a learning project for me.
I thought about create a matrix room (and bridge it probably), because there already is a small amount of people using and testing this.

**Comment by provokateurin** [comment]
The group can be reached under the bridged rooms https://matrix.to/#/#arch-beryllium:matrix.org and https://t.me/arch_beryllium.

**Comment by provokateurin** [comment]
This is fixed, right? So we can close it?

**Comment by jordan89m** [comment]
that side of things, yes. now im getting a broken pipe error on certain packages while running the build script. any pacman tweaks to work around this?

**Comment by provokateurin** [comment]
Huh never seen that. Could you send the logs via some paste service or as file?

**Comment by jordan89m** [comment]
this is what shows up on the serve.sh side of things:

` ----------------------------------------                                    ::ffff:192.168.43.239 - - [24/May/2021 03:00:06] "GET /extra/aarch64/bluez-libs-5.58-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                               ::ffff:192.168.43.239 - - [24/May/2021 03:00:06] "GET /extra/aarch64/bluez-utils-5.58-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                              ::ffff:192.168.43.239 - - [24/May/2021 03:00:18] "GET /extra/aarch64/libsamplerate-0.2.1-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                           ----------------------------------------                                    Exception occurred during processing of request from ('::ffff:192.168.43.239', 39046, 0, 0)                                                             Traceback (most recent call last):                                            File "/data/data/com.termux/files/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread                                                 self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)                   File "/data/data/com.termux/files/usr/lib/python3.9/http/server.py", line 653, in __init__                                                                super().__init__(*args, **kwargs)                                         File "/data/data/com.termux/files/usr/lib/python3.9/socketserver.py", line 747, in __init__                                                               self.handle()                                                             File "/data/data/com.termux/files/usr/lib/python3.9/http/server.py", line 427, in handle                                                                  self.handle_one_request()                                                 File "/data/data/com.termux/files/usr/lib/python3.9/http/server.py", line 415, in handle_one_request                                                      method()                                                                  File "/data/data/com.termux/files/usr/lib/python3.9/http/server.py", line 660, in do_GET                                                                  self.copyfile(f, self.wfile)                                              File "/data/data/com.termux/files/usr/lib/python3.9/http/server.py", line 859, in copyfile                                                                shutil.copyfileobj(source, outputfile)                                    File "/data/data/com.termux/files/usr/lib/python3.9/shutil.py", line 208, in copyfileobj                                                                  fdst_write(buf)                                                           File "/data/data/com.termux/files/usr/lib/python3.9/socketserver.py", line 826, in write                                                                  self._sock.sendall(b)                                                   BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------                                    ::ffff:192.168.43.239 - - [24/May/2021 03:00:18] "GET /extra/aarch64/alsa-utils-1.2.4-2-aarch64.pkg.tar.xz HTTP/1.1" 200 -                              ::ffff:192.168.43.239 - - [24/May/2021 03:00:18] "GET /extra/aarch64/dhcp-4.4.2-2-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                    ::ffff:192.168.43.239 - - [24/May/2021 03:00:18] "GET /extra/aarch64/libnm-1.30.4-3-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                  ::ffff:192.168.43.239 - - [24/May/2021 03:00:19] "GET /extra/aarch64/js78-78.10.1-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                  ::ffff:192.168.43.239 - - [24/May/2021 03:00:21] "GET /extra/aarch64/polkit-0.118-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                  ::ffff:192.168.43.239 - - [24/May/2021 03:00:21] "GET /extra/aarch64/libmm-glib-1.16.4-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                             ::ffff:192.168.43.239 - - [24/May/2021 03:00:21] "GET /extra/aarch64/slang-2.3.2-2-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                   ::ffff:192.168.43.239 - - [24/May/2021 03:00:21] "GET /extra/aarch64/libndp-1.8-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                    ::ffff:192.168.43.239 - - [24/May/2021 03:00:21] "GET /extra/aarch64/libdaemon-0.14-5-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                ::ffff:192.168.43.239 - - [24/May/2021 03:00:22] "GET /extra/aarch64/libsodium-1.0.18-2-aarch64.pkg.tar.xz HTTP/1.1" 200 -                              ::ffff:192.168.43.239 - - [24/May/2021 03:00:22] "GET /extra/aarch64/libteam-1.31-3-aarch64.pkg.tar.xz HTTP/1.1" 200 -                                  ::ffff:192.168.43.239 - - [24/May/2021 03:00:22] "GET /extra/aarch64/mobile-broadband-provider-info-20201225-1-any.pkg.tar.xz HTTP/1.1" 200 -           ::ffff:192.168.43.239 - - [24/May/2021 03:00:22] "GET /extra/aarch64/networkmanager-1.30.4-3-aarch64.pkg.tar.xz HTTP/1.1" 200 -                         ::ffff:192.168.43.239 - - [24/May/2021 03:00:22] "GET /extra/aarch64/xdg-user-dirs-0.17-3-aarch64.pkg.tar.xz HTTP/1.1" 200 -                            ::ffff:192.168.43.239 - - [24/May/2021 03:00:23] "GET /community/aarch64/jansson-2.13.1-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                            ::ffff:192.168.43.239 - - [24/May/2021 03:00:23] "GET /community/aarch64/libnewt-0.52.21-5-aarch64.pkg.tar.xz HTTP/1.1" 200 -                           ::ffff:192.168.43.239 - - [24/May/2021 03:00:23] "GET /community/aarch64/libpgm-5.3.128-1.1-aarch64.pkg.tar.xz HTTP/1.1" 200 -                          ::ffff:192.168.43.239 - - [24/May/2021 03:00:23] "GET /community/aarch64/zeromq-4.3.4-1-aarch64.pkg.tar.xz HTTP/1.1" 200 -'

**Comment by provokateurin** [comment]
Just restart it? I really don't know what it could mean

**Comment by jordan89m** [comment]
Resolved by building a new set of download scripts. I'll upload to my repos after some sleep and you're more than welcome to reference it on yours at that time. :) seemed like missed/partial files. just did 24G and full build in 5 minutes :1st_place_medal:

**Comment by jordan89m** [comment]
Are you sure make_installer.sh is right? because where is makeinstaller.sh?

**Comment by jordan89m** [comment]
i guess "full build" in my above only being img files. cant get a zip out of it.

**Comment by jordan89m** [comment]
Oh man.... hahahahah!

I've got it all figured out. Shoulda known there was some PMOS-Installer git scripts involved....

BUT.. it now want a pin. Unlike PMOS, i was not prompted for one.

**Comment by jordan89m** [comment]
Read further into the build script. All is well now. Closing this issue. I'll hop on matrix in a bit and link you my updated mirror prep repo. :sunglasses:

**Comment by provokateurin** [comment]
Huh I don't understand what your fix is, but nice that it now works!
I'll look at your fix and maybe then I understand what you mean.
